modimport("modifs/base/cosmetic")
modimport("modifs/base/unlocktracker")
modimport("modifs/base/charactercreator")
modimport("modifs/base/characterscreen")

modimport("modifs/colorpicker/playerpostinit")
modimport("modifs/colorpicker/playerpuppet")
modimport("modifs/colorpicker/selectablepuppet")
modimport("modifs/colorpicker/charactercreator")
modimport("modifs/colorpicker/characterscreen")
